package com.rules

import com.harry.droolsdemo.model.Product

rule diamondRule
    when
        productObject : Product(type == Product.DIAMOND,message:"钻石")
    then
        System.out.println(message);
        productObject.setDiscount(15);
    end
rule goldRule
    when
        productObject: Product(type == Product.GOLD,message:"黄金")
    then
        System.out.println(message);
        productObject.setDiscount(25);
    end